name: VervaraFarming
version: ${project.version}
main: redshadus.vervarafarming.Main
api-version: 1.13
commands:
  getpumicestone:
    description: This command gives the player pumice stone
    usage: /getpumicestone